//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tranquility_Login.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tranquility_Login.Localization.zh_CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error 101: 无效的账号格式。已采用默认账号！ 的本地化字符串。
        /// </summary>
        internal static string err_101 {
            get {
                return ResourceManager.GetString("err_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用法：Tranquility-Login &lt;task&gt; [-options]
        ///
        ///其中任务(&lt;task&gt;)包括：
        ///   auto        根据实际情况决定进行clone、pull、configure、start
        ///   clone       获取完整的整合包
        ///   pull        获取最新的整合副本
        ///   configure   自动配置启动器设置
        ///   start | launch
        ///               启动游戏
        ///
        ///其中选项([-options])包括：
        ///   -launcher=[multimc|hmcl]
        ///               配置MultiMC或HMCL启动器的启动设置
        ///   -repo=[:&lt;repository name&gt;] 
        ///               设置本程序获取的整合包地址
        ///   -account=[:&lt;username&gt;@:&lt;password&gt;]
        ///               设置Clone仓库时使用的用户名和密码
        ///   -? | -help  输出此帮助信息
        ///   -version    输出产品版本并退出
        ///   
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HelpData {
            get {
                return ResourceManager.GetString("HelpData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;
        /// 的本地化字符串。
        /// </summary>
        internal static string version_after {
            get {
                return ResourceManager.GetString("version_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Tranquility Login version &quot; 的本地化字符串。
        /// </summary>
        internal static string version_prefix {
            get {
                return ResourceManager.GetString("version_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 101: 识别到无效的任务参数！ 的本地化字符串。
        /// </summary>
        internal static string wrn_101 {
            get {
                return ResourceManager.GetString("wrn_101", resourceCulture);
            }
        }
    }
}
